on:
  push:
    branches:
      - "main"

jobs:
  check-files-changed:
    name: Check files that were changed
    runs-on: ubuntu-latest
    outputs:
      backend: ${{steps.filter.outputs.backend}}
      frontend: ${{steps.filter.outputs.frontend}}
      database: ${{steps.filter.outputs.database}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check files changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
                - "src/libs/server/**"
                - "wrangler.toml"
            frontend:
                - "src/app/**"
                - "src/libs/client/**"
                - "next.config.mjs"
            database:
                - "src/libs/server/src/db/schema.ts"
                - "drizzle.config.ts"
                - "drizzle/*"

  database-backend-frontend:
    needs: "check-files-changed"
    name: Generation and Migration to Production Database -> Cloudflare Workers Hono Production Deployment -> Vercel Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'true' && needs.check-files-changed.outputs.frontend == 'true' && needs.check-files-changed.outputs.database == 'true'}}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Make .dev.vars file for database migration
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
          file_name: .dev.vars

      - name: Database Schema Generation and Migration
        run: pnpm run db:generate && pnpm run db:migrate

      - name: Edit wrangler.toml file
        run: echo 'name = "btl-nextjs-api-prod"' >> wrangler.toml

      - name: Deploy Hono to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  backend-frontend:
    needs: "check-files-changed"
    name: Cloudflare Workers Hono Production Deployment -> Vercel Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'true' && needs.check-files-changed.outputs.frontend == 'true' && needs.check-files-changed.outputs.database == 'false'}}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Edit wrangler.toml file
        run: echo 'name = "btl-nextjs-api-prod"' >> wrangler.toml

      - name: Deploy Hono to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  database-backend:
    needs: "check-files-changed"
    name: Generation and Migration to Production Database -> Cloudflare Workers Hono Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'true' && needs.check-files-changed.outputs.frontend == 'false' && needs.check-files-changed.outputs.database == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Make .dev.vars file for database migration
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
          file_name: .dev.vars

      - name: Database Schema Generation and Migration
        run: pnpm run db:generate && pnpm run db:migrate

      - name: Edit wrangler.toml file
        run: echo 'name = "btl-nextjs-api-prod"' >> wrangler.toml

      - name: Deploy Hono to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  backend:
    needs: "check-files-changed"
    name: Cloudflare Workers Hono Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'true' && needs.check-files-changed.outputs.frontend == 'false' && needs.check-files-changed.outputs.database == 'false'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Edit wrangler.toml file
        run: echo 'name = "btl-nextjs-api-prod"' >> wrangler.toml

      - name: Deploy Hono to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  database-frontend:
    needs: "check-files-changed"
    name: Generation and Migration to Production Database -> Vercel Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'false' && needs.check-files-changed.outputs.frontend == 'true' && needs.check-files-changed.outputs.database == 'true'}}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Make .dev.vars file for database migration
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
          file_name: .dev.vars

      - name: Database Schema Generation and Migration
        run: pnpm run db:generate && pnpm run db:migrate

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  frontend:
    needs: "check-files-changed"
    name: Vercel Production Deployment
    if: ${{needs.check-files-changed.outputs.backend == 'false' && needs.check-files-changed.outputs.frontend == 'true' && needs.check-files-changed.outputs.database == 'false'}}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  database:
    needs: "check-files-changed"
    name: Generation and Migration to Production Database
    if: ${{needs.check-files-changed.outputs.backend == 'false' && needs.check-files-changed.outputs.frontend == 'false' && needs.check-files-changed.outputs.database == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Make .dev.vars file for database migration
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL_PROD}}
          file_name: .dev.vars

      - name: Database Schema Generation and Migration
        run: pnpm run db:generate && pnpm run db:migrate
