import { genres as genresList } from "@/root/src/libs/shared/src/data/genres";
import { SearchObjectType } from "@/root/src/libs/shared/src/schemas";

const genre = [
  ...genresList.map((val) => val.name),
  "Academic",
  "Action",
  "African-American",
  "Architecture",
  "Business",
  "Catholic",
  "Christian",
  "Economics",
  "Health and Wellbeing",
  "Medical",
  "Photography",
  "Politics",
  "Religion",
  "Technology",
];

const publisher = [
  "Professional Writers Help",
  "Writers of USA",
  "Penguin Random House",
  "Harper Collins",
  "Simon and Schuster",
  "Macmillan Publishers",
  "Hachette Book Group",
  "John Wiley and Sons",
  "Merriam-Webster",
  "Scholastic",
  "Pearson",
  "Houghton Mifflin Harcourt",
  "Springer Nature",
  "McGraw-Hill Education",
  "Kodansha",
  "Cengage",
  "Houghton Mifflin Harcourt",
  "Oxford University Press",
  "Shueisha",
  "Turner Publishing",
  "Tin House",
  "Epicenter Press",
  "The MIT Press",
  "Unnamed Press",
  "Chronicle Books",
  "Tilbury House",
  "Holiday House",
  "Uproar Books",
  "Workman Publishing",
  "Blind Eye Books",
  "Chicago Review Press",
  "University of California Press",
  "Stone Pier Press",
  "Taylor & Francis Publishing",
  "Cambridge University Press",
  "Yale University Press",
  "Hot Key Books",
  "Palgrave Macmillan",
  "Flying Eye Books",
  "Puffin Books",
  "Harlequin",
  "Titan Books",
  "Hatch Press",
  "Hay House",
  "Lion Hudson",
  "Hurst Publishers",
  "Hardie Grant Publishing",
  "Hodder & Stoughton",
  "Hart Publishing",
  "Kyle Books",
  "Thames & Hudson",
  "Mills & Boon",
  "Tate Publishing",
  "Royal Society of Medicine Press Ltd",
  "Kube Publishing",
  "Lund Humphries",
  "Little Tiger Press",
  "Edgar Elgar Publishing",
  "ACC Art Books",
  "Bloomsbury Children's Books",
  "Solaris Books",
  "Routledge",
  "Quarto Publishing Group",
  "Balzer and Bray",
  "And Other Stories",
  "Jo Fletcher Books",
  "Canelo",
  "Aria Publishing",
  "Severn House",
  "Saraband",
  "Tilted Axis Press",
  "Joffe Books",
  "Galley Beggar Press",
  "David Fickling Books",
  "Zed Books",
  "Comma Press",
  "Kogan Page Inc.",
  "Watkins",
  "Northodox Press",
  "Claret Press",
  "Shepheard-Walwyn",
  "Grimbold Books",
  "Self Publish, Be Happy",
  "Head of Zeus",
  "Strangers Press",
  "Oldcastle Books",
  "Hogs Back Books",
  "No Exit Press",
  "Influx Press",
  "Bluemoose Books",
  "Fledgling Press",
  "Tartarus Press",
  "Dead Ink Books",
  "Angry Robot",
  "Laurence King Publishing",
  "Piccadilly Publishing",
  "Black Horse Westerns",
  "Alpha Science International Ltd",
  "Equinox Publishing",
  "Morel Books",
  "Al-Hidaayah Publishing",
  "Medina Publishing",
  "Korero Press",
  "Luna Press Publishing",
  "Fitzcarraldo Editions",
  "Imagine That Publishing",
  "Flame Tree Press",
  "Holland Park Press",
  "Ta-Ha Publishers",
  "Peirene Press Ltd",
  "Sapere Books",
  "Peepal Tree",
  "Headpress",
  "Halban Publishers",
  "White Thread Press",
];

export const data = { genre, publisher } as { [key in keyof SearchObjectType]: string[] };
